### ISSUE TITLE
Openvidu is not processing ParticipantLeft event correctly

### ISSUE THREAD

**Issue by sandeep048** [OpenVidu/openvidu#35] opened 2018-03-29 12:41 UTC
Some times when a user leaves openvidu session those streams are still available in the underlying object `OV.openvidu.session.remoteStreams`.

This is causing huge inconvenience since there is no data in those remote streams. Those connections are effectively dead peers.

The following example below has only one remote active stream which is marked with a pointer, rest all are displaying as empty boxes.

![image](https://user-images.githubusercontent.com/500899/38088962-7344448e-337b-11e8-9fb8-2d0c26d028ba.png)

Messages like these are displayed on the console.
`Exception processing request: {"method":"participantLeft","params":{"name":"9mywsdxjjak1zvrm"}}`

Brainstrorming and possible solutions?
- Is there a way to identify which of these remote streams are dead from API?
- Can we some how instruct the server to remove those stale connections so that at least after browser refresh the issue goes away?

**Comment by micaelgallego** [comment] 2018-03-29 13:52
It seems a bug when notifying to other users that some user is gone from a session. 

Can you share with us a simple project to reproduce the problem? This will help us to discover the root cause and fix the bug.

**Comment by aslamky** [comment] 2018-03-30 06:10
Me too facing the same problem.
![screenshot from 2018-03-29 18-40-18](https://user-images.githubusercontent.com/25210869/38126565-1908e440-340f-11e8-985b-398e4ef2acdd.png)

**Comment by pabloFuente** [comment] 2018-04-03 07:47
We are currently undergoing a deep refactoring process in OpenVidu Browser library with the aim of greatly simplifying and cleaning up the code. We will be releasing our first breaking change update with openvidu-browser-2.0.0 in the following days/weeks, and this and other bugs will hopefully be fixed. If this is not the case, it will at least be much easier to deal with them after this refactoring process.

**Comment by flexconstructor** [comment] 2018-04-03 07:52
Thank you for being there. I hope that in the process of refactoring you will not forget about this Issue #15.

**Comment by pabloFuente** [comment] 2018-05-11 09:34
OpenVidu Browser has been refactored in 2.0.0. This should be fixed now.

**Closed by pabloFuente** 2018-05-11 09:34 UTC
