### ISSUE TITLE
Some streams missing from recording

### ISSUE THREAD

**Issue by pjuhasz** [OpenVidu/openvidu#479] opened 2020-05-20 15:46 UTC
**Describe the bug**
We're developing a video application with two participants. We have to record both streams in their entirety. We use recordingMode = ALWAYS and defaultOutputMode = INDIVIDUAL when creating OpenVidu sessions. Sometimes, in more than 50% of the cases, one of the streams is missing from the final zip. Both participants can hear and see each other.

**Expected behavior**
Both streams are recorded and present in the final zip.

**Wrong current behavior**
In some calls, one of the streams is missing from the final zip.
There is only one .webm file in the .zip, and the accompanying .json mentions only one stream.

**OpenVidu tutorial where to replicate the error**
N/A unfortunately

**OpenVidu deployment info**
Custom Docker container based on Ubuntu 16.04, official KMS .deb package and OpenVidu .jar
OpenVidu: 2.14.0
KMS: 6.13.0

**Client device info (if applicable)**
Chrome 81.0.4044.138 on Windows 10 64-bit (both participants)

**Screenshots**
N/A

**Additional context**
From the attached (redacted) log it is apparent that recording was not even started for one of the streams, indeed, there is an ERROR line about that when the recording is stopped.

[openvidu-server-redacted.log](https://github.com/OpenVidu/openvidu/files/4657837/openvidu-server-redacted.log)

**Comment by pabloFuente** [comment] 2020-05-20 15:54
Have you deployed following official instructions? https://docs.openvidu.io/en/stable/deployment/

If not, it'll be very hard for us to replicate your scenario. Unfortunately we can only provide support 
 for deployments following the official instructions (any issue or bug found in the development container is also suitable for us to fix any unexpected behavior). I'm sure you will understand. If we had to help any user deploying the software in any kind of possible way, that would consume all of our time.

Please, try to replicate the issue in an official deployment of OpenVidu, so we may try replicating it. That is: in AWS with CloudFormation or on premises following the instructions. If not, it will be extremely difficult for us to solve any kind of bug.

Regards.

**Comment by pjuhasz** [comment] 2020-05-20 16:11
No, unfortunately neither of the official instruction paths were suitable for our architecture. I'll try to replicate on something you can work with, but it's not that simple.

**Comment by pjuhasz** [comment] 2020-05-20 19:30
In any case I think deployment is irrelevant for this problem.

In our use case the two participants don't necessary join the session and start publishing at the same time: the session is created, one of the participants join, then possibly after several minutes the other participant joins.

From skimming the code in SingleStreamRecordingService.java I got the impression that when a recording (for a session) is started, it gets the list of active publishers for that session and starts to record the stream for each of them, but when it's done, it's done, and publishers that join later will not have their streams included in the recording. And, because we use ALWAYS mode, recording starts early and automatically, so we get hit by this.

Is my interpretation correct?

If yes, is this a bug? Arguably, users joining at different times to a session is a plausible and valid use case, so I think there should be provisions for this. At the very least this case should be documented as a potential pitfall.

**Comment by pabloFuente** [comment] 2020-05-20 19:34
Of course streams being published at any time are recorded. Maybe the deployment is in fact irrelevant, but for us to search a possible bug is necessary to replicate the error in a well-known setup. That's why I was asking if you could try to get the same kind of wrong behavior in any of the official deployments. From that point, we can start looking for unexpected behaviors.

**Comment by pjuhasz** [comment] 2020-05-21 15:04
I was able to reproduce the problem with the development docker container and the openvidu-js-node tutorial. I was wrong about the cause being the long delay between the two streams: it's the opposite, the two streams have to start very close to each other in time. There is a race condition around the administration of the session's recording state.

As far as I understand the situation, the reason is the following:
- When the session is initiated in ALWAYS mode and the first participant joins, RecordingManager.startRecording gets called, which calls singleStreamRecordingService.startRecording, which arranges the stream to be recorded for the one participant who has already joined. This can take some time.
- Now (while the process above is still happening) the second participant joins and KurentoParticipant.publishToRoom gets called in a different thread. This method checks whether recordingManager.sessionIsBeingRecorded.
- However, the underlying hashmap for that check only gets updated in RecordingManager.updateRecordingManagerCollections, only after singleStreamRecordingService.startRecording is finished. Any stream that joins before that time will not be recorded.

Steps to reproduce:
- start the development docker container with the options to enable recording.
- modify the openvidu-js-node tutorial so that it records sessions. 
[ov_record.patch.txt](https://github.com/OpenVidu/openvidu/files/4663105/ov_record.patch.txt)
- start the tutorial's server as documented.
- load https://localhost:5000 in two browser windows.
- log in with publisher1 and publisher2 in the first and second window, respectively.
- ensure that they both want to join to the same session.
- click on JOIN in both windows with as little delay as possible - it's best if you click "remember settings" when it asks for mic and camera permissions so that it doesn't mess up the timing.

The time window in which the bug is triggered is short (about 1 second in our application's case, less than that with the locally ran tutorial), and it seems to depend on how fast the ICE candidate negotiation finishes.

I hope this helps.

**Comment by pabloFuente** [comment] 2020-05-21 15:56
Thank you very much for the report. With this information we can start investigating the issue. If we're able to replicate the error following your instructions, we will fix this ASAP.

Have you used container version 2.14.0?

**Comment by pjuhasz** [comment] 2020-05-21 16:02
Yes, 2.14.0.

**Comment by pabloFuente** [comment] 2020-05-22 15:30
I can confirm that after some in-depth tests and with a bit of luck I have been able to replicate the error. Already working on a fix.

**Comment by pjuhasz** [comment] 2020-05-22 15:45
OK, glad to hear that!

Still, an idea to make replication more deterministic:
Modify the tutorial so that pressing the Join button waits until the next multiple of 20 seconds instead of publishing the stream right away. With this, it fails reliably for me.

[ov_publish_delay.patch.txt](https://github.com/OpenVidu/openvidu/files/4669044/ov_publish_delay.patch.txt)

**Comment by pabloFuente** [comment] 2020-05-23 15:57
Okey, this commit should take care of this concurrency problem: 3374e511ee337a794b5b8a3b8b208cd41be21c00

I've performed some testing, forcing some extreme situations like publishing more than 30 streams at the exact same time in the same session. A session configured with ALWAYS and INDIVIDUAL recording mode. All of the streams seem to be always well-recorded.

We have published a beta version with this fix: [openvidu/openvidu-server:2.14.1-beta4](https://hub.docker.com/layers/openvidu/openvidu-server/2.14.1-beta4/images/sha256-ab395d4910b5d6fce1e6e4e73ade814bc2bb73385ec27ccb08b13210a6c6b57d?context=explore)

Give it a try in a controlled environment to see if the problem is fixed. To try the beta, simply change the openvidu-server [docker image tag in your **`docker-compose.yml`** file](https://github.com/OpenVidu/openvidu/blob/master/openvidu-server/docker/openvidu-docker-compose/docker-compose.yml#L25) and run command **`sudo ./openvidu restart`**

**Comment by pjuhasz** [comment] 2020-05-23 18:26
Thanks!

I was only able to do some rudimentary testing with my Frankenclient, and its seems that both streams were recorded in all my tries.

I've noticed one strange thing: from the log it appeared that the recording for one of the streams has started twice, from two different threads. See the attached log extract, look for str_CAM_VaF3_con_FkDH1NW7PD. The recorded files don't appear to be corrupt, though.

[ov_log_recording_duplicate_stream.txt](https://github.com/OpenVidu/openvidu/files/4672303/ov_log_recording_duplicate_stream.txt)

One more thing: There are other bug reports (e.g. #433) that complain about intermittent recording failures - can they be related to this one?

**Comment by pabloFuente** [comment] 2020-05-23 18:40
The fix may have introduced this new unwanted behavior. Still better than having no recorded file at all for a stream. I'll take a closer look to it, thoguh. Any hint on how to reproduce this new behavior?

Thank you for your answers.

**Comment by pjuhasz** [comment] 2020-05-23 18:59
I used the openvidu-js-node tutorial with the two patches I've attached to earlier comments (from two browser windows on the same machine). It happened only once in about 10 tries, so it may be tricky to reproduce. My silly little patch adds a random delay between 0 and 300 ms, so that the streams don't start at exactly the same time, but with some delay. Perhaps you could try a more sophisticated approach where a synthetic client publishes several streams with tunable delays.

**Comment by pabloFuente** [comment] 2020-05-23 21:15
Okey, I've not been able to reliably replicate the error, but with the log you provided has been enough. This new simple commit should take care of the concurrent initialization of an individual stream recording: f5171c9306c4847fd6d1039bf55042d3677522ae

The same openvidu-server beta container has been overwritten: openvidu/openvidu-server:2.14.1-beta4

Please, give it another try when possible (remember forcing the pull of the same image tag to get the updated one). If you can confirm that this new wrong duplicated thing does not happen anymore in your tests, we will accept this solution and close this issue. Officially available in the next release.

**Comment by pjuhasz** [comment] 2020-05-24 16:14
I couldn't reproduce the duplicate initialization problem with the new image.

Thanks for the quick work!

**Closed** 2020-05-24 16:16 UTC
Labels: bug
