### ISSUE TITLE
Error 500 on active sessions API endpoint after kms reconnection

### ISSUE THREAD

**Issue by miguelrcDEV** [OpenVidu/openvidu#202] opened 2019-02-18 08:54 UTC
Hi!
I think I have detected an error, and that is that when restarting the kms, and correctly reconnecting the openvidu-server, the endpoint of `/api/sessions` that returns the active sessions on the server, returns an error 500 instead of the empty array. For me it is important because before creating a new session, I check several things, and for this I need to call this endpoint. Could you check it in case it was possible that you put a patch?

Thank you.

**Comment by miguelrcDEV** [comment] 2019-02-18 13:23
When restart kms without sessions on openvidu-server, this print a log with reconnection succesful(true):
io.openvidu.server.kurento.kms.FixedOneKmsManager (reconnected) - Kurento Client reconnected (true) to KMS with uri ws://localhost:8888/kurento
But when is a session running, openvidu-server prints reconnection log but with isReconnected to false:
io.openvidu.server.kurento.kms.FixedOneKmsManager (reconnected) - Kurento Client reconnected (false) to KMS with uri ws://localhost:8888/kurento

After this, get active sessions always return a 500 error, like I say in first comment
Could you check this?

**Comment by pabloFuente** [comment] 2019-02-18 13:44
I've checked the behavior you explained. You are right: GET request to /api/sessions returns a 500 error after restarting KMS with active sessions.

The problem is that this ongoing sessions are not really closed and terminated after KMS has disconnected. Every in-memory entity stored in openvidu-server related to these sessions still exists after KMS reconnection, but real media streams do not exist on KMS, of course. So the operation of getting the information for these sessions after KMS has destroyed every media stream fails: no publisher or subscriber streams are found  for any of these sessions.

So the solution has to be carefully planned: do we want ongoing sessions to be automatically and completely closed if openvidu-server loses its connection to KMS, or maybe we prefer to keep them active (that is, any `sessionId` and every created `token` still functional) but to close and clean any publisher or subscriber stream? This way after KMS reconnection, any session that was active when the disconnection occured will appear as a session with the same number of users connected, but with no publisher or subscriber stream. Users could re-publish and re-subscribe to the session this way.

**Comment by miguelrcDEV** [comment] 2019-02-18 14:33
Right now maybe the best is a quick fix, which may be the first option to close all sessions, would that be possible to have it in the next version? Once fixed, the second option is the best and most flexible, but I understand that it is also the most complicated and that it would take more time to develop correctly.
I await your answer to find out if it would be possible for you to have the quick fix (close all sessions) for the next release, because as I said, it is very important for us.

Thanks in advance.

**Comment by pabloFuente** [comment] 2019-02-18 17:53
We are working on it.

**Comment by pabloFuente** [comment] 2019-09-11 13:36
This was fixed a long time ago. Sorry fo the delay closing the issue.

Some light explanations: when OpenVidu detects that KMS has restarted, any active session is processed this way: every active stream is destroyed (as the media server has restarted, we are sure that no WebRTC connection will still be active. Subscribers are just probably seeing a frozen image of the Publisher) with reason `mediaServerDisconnect`. But sessions are still active and clients still connected to them. It is up to the developer on how to react upon these `streamDestroyed` events with reason `mediaServerDisconnect`. For example, the can just re-publish and re-subscribe all of this streams (WebRTC connections will be seamlessly established in the new instance of KMS). The session and the participant metadata won't be lose.

**Closed by pabloFuente** 2019-09-11 13:36 UTC
