### ISSUE TITLE
Remove video coming empty

### ISSUE THREAD

**Issue by luanraithz** [OpenVidu/openvidu#185] opened 2019-01-30 11:38 UTC
I'm having some problems in production with remote videos, I've deployed the openvidu container for testing with the following command:
```
docker run -d --name openvidu -p 4443:4443 --rm -e openvidu.secret=MY_SECRET -e openvidu.publicurl=https://myAWSURL:4443/ -e KMS_STUN_IP=stun.l.google.com -e KMS_STUN_PORT=19302 -e KMS_TURN_URL=some@user.com:password@numb.viagenie.ca openvidu/openvidu-server-kms:2.7.0
``` 

And my client side is running with following code to start openvidu: 
```javascript 
this.OV = new OpenVidu()
this.OV.setAdvancedConfiguration({
    iceServers:  [
        {
             url: 'turn:numb.viagenie.ca',
             credential: 'password',
             username: 'some@user.com'
        }, {
             urls: ["stun:stun.l.google.com:19302"]
            }
     ]
})
const session = this.OV.initSession()
```
And that is the result of [trickle ice test] (https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/) with the turn server:
![image](https://user-images.githubusercontent.com/27583162/51978657-dda51a00-2471-11e9-89d2-63381ee8f7d8.png)

And it still failing to get remote video, the signaling process works apparently fine ( as my local peer receives the remote stream) but the remote stream always comes empty, when I test running to container at my own machine, everything works fine, but when on AWS doesn't work at all.
What am I doing wrong?

**Comment by pabloFuente** [comment] 2019-01-30 12:47
You can try opening all ports in your AWS machine, to see if it is a firewall problem.

**Comment by luanraithz** [comment] 2019-01-31 22:53
Thanks for the fast answer, I will try it as soon as I can.

**Comment by oisnot** [comment] 2019-02-18 12:51
Try running a command like this in javascript console once the pageis loaded and connections established and see if it works. This helps if the thumbnail video doesnt work but clicking on it displays the large video. 

Make sure you store session variable somewhere you can get to it (during development). 

$("#<remotevideoid>").get(0).srcObject = session.remoteConnections[<remoteVideoNodeId>].stream.mediaStream;

Where $("#<remotevideoid>") is the thumbnail video element.

**Comment by luanraithz** [comment] 2019-02-18 13:54
@oisnot I've already tried your suggestion, all the remote videos are really coming blank, I couldn't try @pabloFuente suggestion yet. Thanks

**Comment by Gelmo** [comment] 2019-04-11 01:39
Worth noting that this is reproducible on the official demos, too:

https://demos.openvidu.io

**Comment by micaelgallego** [comment] 2019-04-11 03:51
Can you describe what kind of test are you doing? We have tested
demos.openvidu.io and they work for us.

Thank you

**Comment by Gelmo** [comment] 2019-04-11 04:41
Computer 1:
	Go to https://demos.openvidu.io
	Click GO
	Click Getaroom
	Select Allow on camera permission prompt
	Local camera working
	Select "Share the URL"

Computer 2:
	Open URL that was acquired from Computer 1
	Select Allow on camera permission prompt
	Local camera working

At this point, both computers see their own camera, and there is a black space in place of the video from the other computer.

That being said, I am no longer able to reproduce this. Assuming nothing has changed on your end, this must have been a local issue. I am going to continue testing my deployment and I'll update this issue.

**Comment by Gelmo** [comment] 2019-04-11 04:47
I'm still having this issue on my deployment, but now that I cannot reproduce this behavior on your demo I think it's safe to say that this is an issue with my network configuration rather than the server/frontend. I'm not sure what was causing the same behavior on the public demo; perhaps caching of some sort. Closing issue. Thanks for the quick response!

**Closed** 2019-04-11 08:27 UTC

**Comment by franziz** [comment] 2020-08-06 07:14
I am having the same issue. Sometimes remote video comes empty. Sometimes, not always. I deploy the server inside Docker and using AWS Lightsail due to generous bandwidth. Anyone comes with the same issue?
