### ISSUE TITLE
Sometimes webrtcendpoint is null when adding candidates

### ISSUE THREAD

**Issue by techcouncilbox** [OpenVidu/openvidu#455] opened 2020-04-30 11:39 UTC
**Describe the bug**
We are facing sometimes that openvidu is trying to addcandidates to null webRTCEndpoint and when occurs this participant is not connected to session and conference fails. Most of time is solved reloading page... but it is a big problem.

Logs obtained are something like this:
![image](https://user-images.githubusercontent.com/17164419/80705758-45b83500-8ae7-11ea-9188-994a3caf13b0.png)

After checking the source code we suspect that sometimes onSuccess call:

![image](https://user-images.githubusercontent.com/17164419/80705806-61234000-8ae7-11ea-8ae6-a16e16ed8b74.png)

is not executed before internalAddIceCandidate:

![image](https://user-images.githubusercontent.com/17164419/80705870-8912a380-8ae7-11ea-93b7-be222bfeca94.png)

**Expected behavior**
Wait for the endpoint is created after set values for candidates.

**Wrong current behavior**
Described above

**OpenVidu tutorial where to replicate the error**
We cannot reproduce easily, only in production environment with medium-high loads.

**OpenVidu deployment info**
Version 2.13.0
Kurento 6.13.1
Docker compose installation

**Client device info (if applicable)**
- Chrome 80+ (Official Build) (64-bit) on Windows 7-10, Mac and Linux

**Screenshots**
Showed above.

**Comment by techcouncilbox** [comment] 2020-04-30 12:11
We propose this solution:


`public synchronized Endpoint createEndpoint(CountDownLatch endpointLatch) {
        Endpoint old = this.getEndpoint();
        if (old == null) {
            internalEndpointInitialization(endpointLatch);
        } else {
            endpointLatch.countDown();
        }
        if (this.isWeb()) {
			long startTime = System.currentTimeMillis(); //fetch starting time
            while (this.getEndpoint() == null && (System.currentTimeMillis()-startTime)<10000) {
            }
			old = this.getEndpoint();
			if (old != null) {
				while (!candidates.isEmpty()) {
					internalAddIceCandidate(candidates.removeFirst());
				}
			} else {
				log.error("Error creating endpoint. Timeout expired {}: {}", endpointName,"");
			}

        }
        return old;
    }`

**Comment by techcouncilbox** [comment] 2020-04-30 12:11
We propose this solution:

> public synchronized Endpoint createEndpoint(CountDownLatch endpointLatch) {
        Endpoint old = this.getEndpoint();
        if (old == null) {
            internalEndpointInitialization(endpointLatch);
        } else {
            endpointLatch.countDown();
        }
        if (this.isWeb()) {
			long startTime = System.currentTimeMillis(); //fetch starting time
            while (this.getEndpoint() == null && (System.currentTimeMillis()-startTime)<10000) {
            }
			old = this.getEndpoint();
			if (old != null) {
				while (!candidates.isEmpty()) {
					internalAddIceCandidate(candidates.removeFirst());
				}
			} else {
				log.error("Error creating endpoint. Timeout expired {}: {}", endpointName,"");
			}

        }
        return old;
    }

**Comment by techcouncilbox** [comment] 2020-04-30 12:12
**Solution proposed:**

`public synchronized Endpoint createEndpoint(CountDownLatch endpointLatch) {
        Endpoint old = this.getEndpoint();
        if (old == null) {
            internalEndpointInitialization(endpointLatch);
        } else {
            endpointLatch.countDown();
        }
        if (this.isWeb()) {
			long startTime = System.currentTimeMillis(); //fetch starting time
            while (this.getEndpoint() == null && (System.currentTimeMillis()-startTime)<10000) {
            }
			old = this.getEndpoint();
			if (old != null) {
				while (!candidates.isEmpty()) {
					internalAddIceCandidate(candidates.removeFirst());
				}
			} else {
				log.error("Error creating endpoint. Timeout expired {}: {}", endpointName,"");
			}

        }
        return old;
    }`

**Comment by pabloFuente** [comment] 2020-04-30 12:43
Hi,

The solution is probably just as easy as adding the "early" candidates on the success callback itself.

I've already committed a possible solution: https://github.com/OpenVidu/openvidu/commit/a922b95d9551c32c3b5fe084b99b20731de0af32

How have you deployed OpenVidu? Would it be possible for you to try a beta version with this fix when it is available to see if the error is gone?

Regards.

**Comment by techcouncilbox** [comment] 2020-04-30 12:58
Ok, your solution looks like fine. 

We can check this beta version  right now but we need a docker image...

**Comment by pabloFuente** [comment] 2020-04-30 13:09
Sure, I will provide you the beta version once is up in Dockerhub. No other container will need an update, just openvidu-server

**Comment by pabloFuente** [comment] 2020-04-30 13:53
Nothing. If you look into it a little further is just a way to protect concurrent subscriber endpoint initializations.

**Comment by micaelgallego** [comment] 2020-05-03 20:53
@techcouncilbox do you have a unit test reproducing the issue? If so, please share it with us.

**Comment by techcouncilbox** [comment] 2020-05-04 11:32
We cannot provide that, only production logs. With alpha container problem looks like was fixed.

We will monitorize next days.

**Comment by pabloFuente** [comment] 2020-05-04 17:31
Thanks, tell us if you see the error again.

**Comment by pabloFuente** [comment] 2020-05-12 19:02
The fix is already included in OpenVidu 2.14.0. Please, give it a try to see if the problem is gone.

**Closed by pabloFuente** 2020-05-12 19:02 UTC
Labels: bug
