### ISSUE TITLE
Openvidu server holding empty session

### ISSUE THREAD

**Issue by gvnramu** [OpenVidu/openvidu#428] opened 2020-04-12 06:56 UTC
Hi, When I close browser unexpectedly or browser crashes or the connection is not closed by the user. The API  GET   /api/sessions is always returning the empty session like this `{"numberOfElements":1,"content":[{"sessionId":"20007","createdAt":1586615253453,"mediaMode":"ROUTED","recordingMode":"ALWAYS","defaultOutputMode":"COMPOSED","defaultRecordingLayout":"BEST_FIT","customSessionId":"20007","connections":{"numberOfElements":0,"content":[]},"recording":false}]}`  it is only clearing when the server is restarted. Please help me

**Comment by pabloFuente** [comment] 2020-04-12 09:45
Hi,

This situation may happen in 2.12.0 version and before. But is not probably caused by the client forcibly leaving the session, there are other reasons why sessions with 0 participants may get stuck. Especially if you cannot delete it through REST API.

This possible reasons have been already addressed and will be included in next release 2.13.0, scheuled for next week. Stay tuned!

**Closed by pabloFuente** 2020-04-12 09:45 UTC
Labels: bug
