### ISSUE TITLE
OpenVidu issue with adding custom domain.

### ISSUE THREAD

**Issue by maxifjaved** [OpenVidu/openvidu#25] opened 2018-01-31 20:06 UTC
I am trying to install openvidu server using (aws deployment instructions)[http://openvidu.io/docs/deployment/deploying-aws/]. It is working fine when i am using selfassigned certificated. Steps what i did:

 - Created the openvidu selfassigned using cloudformation
 - Login to the instance and setup ssl using [This Link](https://github.com/maxifjaved/setup-secure-server)
- Create a subdomin on aws Route53 and configure the ssl. [Link](https://contributecloud.digitaldot.io:8443/)

- But it still show the unsecure error (Reason: it point to the base url the openvidu cloudformation created). how i directly open the my custom domain so it doesn't show unsecure window.

##### what i have done till now:
- try to add a custom domain with let's encrypt i.e `digitaldot.io` + `elastic ip` but it fails and rollback.
- also try with the subdomin after associate that elastic ip to a subdomain and add subdomain to letsencrypt custom url

Thanks

**Comment by pabloFuente** [comment] 2018-02-01 16:09
I understand you have a custom domain of your own. Why don't you try OpenVidu CloudFormation deployment with Let's Encrypt? Here is the middle blue column:

[http://openvidu.io/docs/deployment/deploying-aws#4-complete-the-configuration-fields](http://openvidu.io/docs/deployment/deploying-aws#4-complete-the-configuration-fields)

Simply fill the fields with the appropiate values and you will have OpenVidu deployed on your custom domain with an automatic, valid and free certificate.

Regards.

**Comment by maxifjaved** [comment] 2018-02-01 17:40
LET'S ENCRYPT CERTIFICATE

Stack name  - OpenVideo
Type of SSL Certificate - letsencrypt
Email - asif.javed@digitaldot.io
Fully qualified domain name - digitaldot.io (Rote53 is configure and ns are added to the domain host)
Elastic IP - some ip(created at aws)
CRT File - null
KEY File - null
OpenVidu Secret - XYZZZ
Instance Type - t2.medium
KeyName - my pricate ssh key.

It fails and don't create instance.

**Comment by nordri** [comment] 2018-02-01 18:18
It seems like you aren't registering properly your Domain.
Keep in mind that the Elastic IP you set up on the tamplate has to be registered on Route53 in advance. So when you launch the instance it can generate the Let's Encrypt Cert.

So, say you have an ElasticIP 54.54.21.21, then this IP has to resolve to you Fully Qualified Domain Name. You can check this by doing:

`nslookup 54.54.21.21`
or
`nslookup FQDN`

from a Linux terminal.

cheers

**Comment by maxifjaved** [comment] 2018-02-01 20:56
I follow the same process here are the console logs
Domain : contributecloud-live.digitaldot.io
Elastic IP: 18.218.233.45 

![1](https://user-images.githubusercontent.com/17304812/35702811-ec6442a6-07bb-11e8-97ac-77981714bac0.png)

![2](https://user-images.githubusercontent.com/17304812/35702815-f0bfc7bc-07bb-11e8-9a97-622a67649861.png)

**Comment by nordri** [comment] 2018-02-02 07:36
OK.
Could you please send us the **Parameters** you set up on your deployment?
For some reason, it's giving you a timeout because OpenVidu can't start...

**Comment by maxifjaved** [comment] 2018-02-02 19:33
-  Amazon S3 template URL : `https://s3-eu-west-1.amazonaws.com/aws.openvidu.io/CF-OpenVidu-latest.json` 
- 
![Specify Details](https://user-images.githubusercontent.com/17304812/35751265-addf2528-0879-11e8-83be-e03aa330c7d8.png)

**Comment by nordri** [comment] 2018-02-02 21:14
Looks good to me.
Have you tried to deploy again?
Maybe took a while to sync with the DNS

**Comment by maxifjaved** [comment] 2018-02-02 21:26
Yes, i did couple of times but still the same issue. i confirmed the IP using `dig contributecloud-live.digitaldot.io`.

**Comment by maxifjaved** [comment] 2018-02-02 21:45
Just try still getting the same error: 

![aws openvidu faild log](https://user-images.githubusercontent.com/17304812/35756223-4b2c99c0-088c-11e8-81fc-ff72c49352c0.png)

**Comment by talentedandrew** [comment] 2018-02-03 09:05
I'm having the same problem. I tried a couple of times. 


![image](https://user-images.githubusercontent.com/15646138/35765695-6591d1aa-08ef-11e8-875e-fd575c8b6fb4.png)

**Comment by nordri** [comment] 2018-02-05 09:05
OK guys, that's weird.
Would you mind try to deploy again but this time in the wizard, in the last screen, under *Advanced* check *No* under *Rollback on failure* so the EC2 instance will remain when the deploy fails.
Then you can log into the instance and show us this file:
`/var/log/cloud-init-output.log`
That file shows all the operations we've to made to deploy OpenVidu.
Thanks.

**Comment by talentedandrew** [comment] 2018-02-05 09:31
Ok.

**Comment by talentedandrew** [comment] 2018-02-05 10:00
[test.log](https://github.com/OpenVidu/openvidu/files/1694609/test.log)

@nordri This is the file you mentioned.

**Comment by nordri** [comment] 2018-02-05 10:40
Thanks @talentedandrew 
We can see that the problem is with AWS python boostrap package, but we don't know why. That package is provided by AWS itself so we don't have much control over it. It shouldn't fail at all.
We need more information because, here (**eu-west-1** and **us-west-1**) it works correct.
Which AWS region are you using?
Have you tried to deploy self signed certificate (it's the simplest one) 
Please, provide any single details no matter what, we are really intriged by this behavior.
Thank you very much.

**Comment by talentedandrew** [comment] 2018-02-05 10:51
Hi @nordri 

Thanks for your quick response. I'm using N. Virginia AWS region. I have not tried using self signed certificate. (Previously I had used that. But it(certificate) had some issues with the chrome browser).
Let me try with eu-west-1 or us-west-1 regions and check if it works. I'll provide you the details after doing that.

**Comment by maxifjaved** [comment] 2018-02-05 11:20
@nordri self-assigned is working well. It fails when we try a custom domain.

**Comment by talentedandrew** [comment] 2018-02-05 11:25
@nordri it failed on both eu-west-1 and us-west-1 regions with letsencrypt cert.

**Comment by pabloFuente** [comment] 2018-02-05 11:42
Hi @talentedandrew,

Okey, by comparing your log with a succesful one, we can see exactly wich are the differences:

![selection_109](https://user-images.githubusercontent.com/15049534/35802700-51fc75f4-0a71-11e8-9d13-cbfdfdd7facc.png)

So both logs are equal until line 685, where the download of the package `https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz` seems to fail in your instance. That's pretty weird, since it is a public available package provided by Amazon to manage CloudFormation settings. The command that finally fails seems to be:

`pip install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz`

So, to get more information, would you mind executing again the CloudFormation Stack (without ROLLBACK), connect to it through ssh and executing this exact command?:

`sudo pip install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz`

Post the output here, please.

Thanks.

**Comment by talentedandrew** [comment] 2018-02-05 11:45
@pabloFuente Ok sure. I will post the output after doing this.

**Comment by talentedandrew** [comment] 2018-02-05 12:09
@pabloFuente below is the output of `sudo pip install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz`

`The directory '/home/ubuntu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ubuntu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
  Downloading https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz (463kB)
    100% |████████████████████████████████| 471kB 1.0MB/s 
  Requirement already satisfied (use --upgrade to upgrade): aws-cfn-bootstrap===1.4 from https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): python-daemon<2.0,>=1.5.2 in /usr/local/lib/python2.7/dist-packages (from aws-cfn-bootstrap===1.4)
Requirement already satisfied (use --upgrade to upgrade): pystache>=0.4.0 in /usr/local/lib/python2.7/dist-packages (from aws-cfn-bootstrap===1.4)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/dist-packages (from aws-cfn-bootstrap===1.4)
Requirement already satisfied (use --upgrade to upgrade): lockfile>=0.9 in /usr/local/lib/python2.7/dist-packages (from python-daemon<2.0,>=1.5.2->aws-cfn-bootstrap===1.4)
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
`

**Comment by nordri** [comment] 2018-02-05 12:56
Thanks @talentedandrew 
Are you using AWS Route53 as DNS provider?

**Comment by talentedandrew** [comment] 2018-02-05 14:26
@nordri No, I'm not using AWS Route53 as DNS provider.

**Comment by maxifjaved** [comment] 2018-02-05 15:09
@nordri i have the same issue. i am using Route53 as DNS provider.

**Comment by maxifjaved** [comment] 2018-02-05 15:21
@nordri i try over **eu-west-1** and **us-west-1** still have same issue.

**Comment by nordri** [comment] 2018-02-05 15:44
Yeah @maxifjaved I know you're using Route53. I was trying to find a common point between yours issue. Would you mind to send the logs?

@talentedandrew I can see in your last log that you tried to register against Lets Encrypt a few times in a row so you have been temporaly banned. Try again in a couple hours. Find more information here: https://letsencrypt.org/docs/rate-limits/

**Comment by talentedandrew** [comment] 2018-02-05 15:49
@nordri  Thanks for the information :+1: 
Were you able to find any issues from the logs that's causing it to fail?

**Comment by nordri** [comment] 2018-02-05 16:13
@talentedandrew: I'm afraid I'm not. It's quite strange because I've deployed in another Regions with success. I can't reproduce the error.

**Comment by talentedandrew** [comment] 2018-02-05 16:32
@nordri ok. I will give a few more tries and try to provide any details that could help out.

**Comment by maxifjaved** [comment] 2018-02-05 17:21
Here is the log.
[cloud-init-output.log](https://github.com/OpenVidu/openvidu/files/1696114/cloud-init-output.log)

**Comment by nordri** [comment] 2018-02-06 13:11
Hi guys,
We've just released a new version. Now, OpenVidu supports video recording.
Have a try! Follow the same steps as before.
Looking forward to hearing from you.

**Comment by maxifjaved** [comment] 2018-02-06 14:58
That's great. i will try that. Any update on ssl issue.

**Comment by nordri** [comment] 2018-02-06 15:04
Nothing for now.
We expect that an exotic mixture of circumstances has been the reason of that problem and, with the new version, it's been erased.

**Comment by maxifjaved** [comment] 2018-02-06 15:28
When we deploy openvidu using selfassign certificate it output the url, by using that we can connct to our openvidu server. How can we update that public url. I installed certificate manually but it still point to the older url. I updated the nginx configs.

**Comment by nordri** [comment] 2018-02-06 15:35
That public URL is generated by CloudFormation and cannot be changed. If you're using your own DNS you can point to the instance after associate the ElasticIP.
But I encourage you to follow the steps we provided to deploy OpenVidu with Let's Encrypt.

**Comment by maxifjaved** [comment] 2018-02-08 20:12
@nordri i know you are very busy with other stuff as well. Just want to ask, any good news related to this issue? Any expected time period. cloudformation template is updated i just tried. But still have same error.

My application is in production it show 
![Alert popup](https://user-images.githubusercontent.com/17304812/35995608-bbd41862-0d35-11e8-8976-8a449f8cfab5.png) so i need to resolve this as soon as i can. Couple of months ago i try to deploy native go errors. here is that ![issue link](https://github.com/OpenVidu/openvidu/issues/8)

**Comment by micaelgallego** [comment] 2018-02-08 21:55
You need to use a site domain, use an elastic IP and generate a Lets
Encrypt certificate associated to it.

Have you tried that?

El 8 feb. 2018 9:12 p. m., "Muhammad Asif Javed" <notifications@github.com>
escribió:

@nordri <https://github.com/nordri> i know you are very busy with other
stuff as well. Just want to ask, any good news related to this issue? Any
expected time period. cloudformation template is updated i just tried. But
still have same error.

My application is in production it show
[image: Alert popup]
<https://user-images.githubusercontent.com/17304812/35995608-bbd41862-0d35-11e8-8976-8a449f8cfab5.png>
so i need to resolve this as soon as i can. Couple of months ago i try to
deploy native go errors. here is that [image: issue link]
<https://github.com/OpenVidu/openvidu/issues/8>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/OpenVidu/openvidu/issues/25#issuecomment-364233992>,
or mute
the thread

**Comment by nordri** [comment] 2018-02-09 09:01
Hi @maxifjaved 
That warning means that you're serving your app through port 3000 but the OpenVidu' websocker is still on the AWS URL and port.
Please, redeploy using the template we provided. It's the easier way.

**Comment by maxifjaved** [comment] 2018-02-09 21:01
@nordri every time i tried using template it fails and rollback :broken_heart: 

My openvidu server link is [Here](https://contributecloud.digitaldot.io:8443/). It's secret is `MY_SECRET` when i try this url in my application it show the alert un-trusted certificate. In network call it connecting to `ec2-18-218-210-238.us-east-2.compute.amazonaws.com:8443` this is unsecure. so it ask to accept un-trusted certificate. Why is it?

You can test this on this (URL)[https://contribute.cloud/lecture?id=599adba223848e43d3ad8716&sessionId=137108]

Application Login Details: 

username: axif.javed@gmail.com
password: axif.javed@gmail.com

**Comment by nordri** [comment] 2018-02-12 07:48
> My openvidu server url is https://contributecloud.digitaldot.io:8443 and it is showing alert for ec2-18-218-210-238.us-east-2.compute.amazonaws.com:8443
That's because you deployed using self signed cert.
As we recommended you before. You should deploy using the template for Let's Encrypt.
If it still fails, please send me the log so we can check the issue.

**Comment by maxifjaved** [comment] 2018-02-15 05:25
Let's Encrypt working now.
Thanks.

**Comment by nordri** [comment] 2018-02-15 07:38
We're happy you finally could make it!

**Comment by talentedandrew** [comment] 2018-03-07 16:34
@nordri  I'm still getting the error in creating the stack. Below is the log file. Could you please provide any solution for this?
[openvidu_cf_error1.log](https://github.com/OpenVidu/openvidu/files/1789962/openvidu_cf_error1.log)

My instance is located in us-west-1c and is of type t2.xlarge.

**Comment by nordri** [comment] 2018-03-07 18:09
OK @talentedandrew It's suppoused to be fixed now.
Happened one of the instrucctions in the script was pointed an old file in the filesystem.
My bad!

**Comment by talentedandrew** [comment] 2018-03-07 18:26
@nordri thanks for the quick help. I can confirm its fixed now. :+1:

**Comment by maxifjaved** [comment] 2018-05-16 14:41
How to re-new the ssl. It is expired and my application stopped working.

![screenshot from 2018-05-16 19-41-14](https://user-images.githubusercontent.com/17304812/40124089-2c89bede-5941-11e8-8823-7c8524efeab9.png)

**Comment by nordri** [comment] 2018-05-16 14:55
Hello @maxifjaved  would you mind to open a new issue so we can keep every one in a single thread and help other users to find information?
Cheers

**Closed by nordri** 2018-05-16 14:55 UTC

**Comment by expresspotato** [comment] 2018-10-24 21:59
This wasn't working for me and it would crash with expectation failed (timedout). It ended up being the stack name. **hv-video** did not work, plain **video** did.

**Comment by nordri** [comment] 2018-10-25 07:34
Hi @expresspotato 
I'm not sure which is your problem. Our CI system test our cloudformation template using hyphens so definitely you can deploy a stack with hyphens in the name.
Would you mind to continue in this [issue](https://github.com/OpenVidu/openvidu/issues/131) so will be easier for other user to find useful information?
All the best!
