### ISSUE TITLE
iOS 13.4 - 'beforeunload' deprecated for 'pagehide'

### ISSUE THREAD

**Issue by hoivikaj** [OpenVidu/openvidu#420] opened 2020-04-03 15:15 UTC
**Describe the bug**
FROM: https://openvidu.discourse.group/t/ios-safari-app-close-does-not-disconnect/377/10 
Starting with Safari in iOS 13.4, the beforeunload event does not call on page refresh as its deprecated per apple. Use of a listener for pagehide is required to see this event.

**Expected behavior**
Refreshing the browser will disconnect the connection and start a new one.

**Wrong current behavior**
Refreshing the browser starts a new connection, leaving the previous connection in the session.

**OpenVidu tutorial where to replicate the error**
Join the a session using getaroom from iOS 13.4, refresh the page. You will see two sessions from the same device, one defunct.

**OpenVidu deployment info**
OpenVidu-Server Ubuntu via Java JAR, openvidu-browser using getaroom demo.

**Client device info (if applicable)**
Describe the client device(s) or platform(s) where you are able to replicate the error. For example:
iOS 13.4 Safari

**Additional context**
https://openvidu.discourse.group/t/ios-safari-app-close-does-not-disconnect/377/10

https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/HandlingEvents/HandlingEvents.html#//apple_ref/doc/uid/TP40006511-SW5

**Comment by pabloFuente** [comment] 2020-04-03 15:19
This is not a bug/limitation/behavior that can be fixed in repository OpenVidu/openvidu.
This must be addressed in the specific repository implementing an iOS 13.4 application, as it is an aspect at the application level, not openvidu-browser library level.

Closing this. Open it again where appropriate. Thanks.

**Closed by pabloFuente** 2020-04-03 15:19 UTC
Labels: bug
