### ISSUE TITLE
Cannot get openvidu-server to run on Ubunut 18.04

### ISSUE THREAD

**Issue by FXschwartz** [OpenVidu/openvidu#280] opened 2019-06-26 03:11 UTC
Hi openvidu team! Awesome project you guys have and am really enjoying it. I've currently got it working with the AWS template but am trying to set it up on my own Ubuntu 18.04 server. I followed the documentation and I've flailed for a while now and hoping you can help me.

When I run -
It appears to be starting up just fine but after a couple of minutes it dumps out this

```[WARN] 2019-06-25 22:05:37,990 [ntExec-e2-t0] io.openvidu.server.kurento.kms.FixedOneKmsManager (connectionFailed) - Kurento Client failed connecting to KMS with uri ws://localhost:8888/kurento
[WARN] 2019-06-25 22:05:38,006 [main] org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext (refresh) - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'recordingManager': Unsatisfied dependency expressed through field 'sessionHandler'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sessionEventsHandler': Unsatisfied dependency expressed through field 'CDR'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'cdr': Unsatisfied dependency expressed through field 'sessionManager'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sessionManager': Unsatisfied dependency expressed through field 'kcProvider'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'kmsManager' defined in io.openvidu.server.OpenViduServer: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.openvidu.server.kurento.KurentoClientProvider]: Factory method 'kmsManager' threw exception; nested exception is org.kurento.commons.exception.KurentoException: Exception connecting to KMS
[WARN] 2019-06-25 22:05:38,007 [atExec-e1-t0] org.kurento.jsonrpc.client.JsonRpcClientNettyWebSocket (connectNativeClient) - [KurentoClient]  ERROR connecting WS Netty client, opening channel
java.lang.InterruptedException: null
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:231)
        at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:131)
        at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:30)
        at io.netty.util.concurrent.DefaultPromise.sync(DefaultPromise.java:337)
        at io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:119)
        at io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:30)
        at org.kurento.jsonrpc.client.JsonRpcClientNettyWebSocket.connectNativeClient(JsonRpcClientNettyWebSocket.java:254)
        at org.kurento.jsonrpc.client.AbstractJsonRpcClientWebSocket.internalConnectIfNecessary(AbstractJsonRpcClientWebSocket.java:711)
        at org.kurento.jsonrpc.client.AbstractJsonRpcClientWebSocket.connectIfNecessary(AbstractJsonRpcClientWebSocket.java:847)
        at org.kurento.jsonrpc.client.AbstractJsonRpcClientWebSocket.internalSendRequestWebSocket(AbstractJsonRpcClientWebSocket.java:352)
        at org.kurento.jsonrpc.client.AbstractJsonRpcClientWebSocket$1.internalSendRequest(AbstractJsonRpcClientWebSocket.java:141)
        at org.kurento.jsonrpc.internal.JsonRpcRequestSenderHelper.sendRequest(JsonRpcRequestSenderHelper.java:75)
        at org.kurento.jsonrpc.internal.JsonRpcRequestSenderHelper.sendRequest(JsonRpcRequestSenderHelper.java:69)
        at org.kurento.jsonrpc.internal.JsonRpcRequestSenderHelper.sendRequest(JsonRpcRequestSenderHelper.java:99)
        at org.kurento.jsonrpc.client.JsonRpcClient.sendRequest(JsonRpcClient.java:122)
        at org.kurento.jsonrpc.client.JsonRpcClient$1.run(JsonRpcClient.java:262)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[INFO] 2019-06-25 22:05:38,009 [main] org.apache.catalina.core.StandardService (log) - Stopping service Tomcat
[INFO] 2019-06-25 22:05:38,031 [main] org.springframework.boot.autoconfigure.logging.AutoConfigurationReportLoggingInitializer (logAutoConfigurationReport) -

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
[ERROR] 2019-06-25 22:05:38,036 [main] org.springframework.boot.SpringApplication (reportFailure) - Application startup failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'recordingManager': Unsatisfied dependency expressed through field 'sessionHandler'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sessionEventsHandler': Unsatisfied dependency expressed through field 'CDR'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'cdr': Unsatisfied dependency expressed through field 'sessionManager'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sessionManager': Unsatisfied dependency expressed through field 'kcProvider'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'kmsManager' defined in io.openvidu.server.OpenViduServer: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.openvidu.server.kurento.KurentoClientProvider]: Factory method 'kmsManager' threw exception; nested exception is org.kurento.commons.exception.KurentoException: Exception connecting to KMS
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:592)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:370)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1219)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:551)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:754)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175)
        at io.openvidu.server.OpenViduServer.main(OpenViduServer.java:195)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:521)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sessionEventsHandler': Unsatisfied dependency expressed through field 'CDR'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'cdr': Unsatisfied dependency expressed through field 'sessionManager'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sessionManager': Unsatisfied dependency expressed through field 'kcProvider'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'kmsManager' defined in io.openvidu.server.OpenViduServer: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.openvidu.server.kurento.KurentoClientProvider]: Factory method 'kmsManager' threw exception; nested exception is org.kurento.commons.exception.KurentoException: Exception connecting to KMS
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:592)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:370)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1219)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:551)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:207)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1131)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1059)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:589)
        ... 27 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'cdr': Unsatisfied dependency expressed through field 'sessionManager'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sessionManager': Unsatisfied dependency expressed through field 'kcProvider'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'kmsManager' defined in io.openvidu.server.OpenViduServer: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.openvidu.server.kurento.KurentoClientProvider]: Factory method 'kmsManager' threw exception; nested exception is org.kurento.commons.exception.KurentoException: Exception connecting to KMS
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:592)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:370)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1219)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:551)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:207)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1131)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1059)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:589)
        ... 40 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sessionManager': Unsatisfied dependency expressed through field 'kcProvider'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'kmsManager' defined in io.openvidu.server.OpenViduServer: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.openvidu.server.kurento.KurentoClientProvider]: Factory method 'kmsManager' threw exception; nested exception is org.kurento.commons.exception.KurentoException: Exception connecting to KMS
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:592)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:370)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1219)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:551)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:207)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1131)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1059)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:589)
        ... 53 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'kmsManager' defined in io.openvidu.server.OpenViduServer: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.openvidu.server.kurento.KurentoClientProvider]: Factory method 'kmsManager' threw exception; nested exception is org.kurento.commons.exception.KurentoException: Exception connecting to KMS
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1128)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1022)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:512)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:207)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1131)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1059)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:589)
        ... 66 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.openvidu.server.kurento.KurentoClientProvider]: Factory method 'kmsManager' threw exception; nested exception is org.kurento.commons.exception.KurentoException: Exception connecting to KMS
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
        ... 78 common frames omitted
Caused by: org.kurento.commons.exception.KurentoException: Exception connecting to KMS
        at org.kurento.client.KurentoClient.<init>(KurentoClient.java:259)
        at org.kurento.client.KurentoClient.create(KurentoClient.java:156)
        at org.kurento.client.KurentoClient.create(KurentoClient.java:140)
        at io.openvidu.server.kurento.kms.FixedOneKmsManager.<init>(FixedOneKmsManager.java:48)
        at io.openvidu.server.kurento.kms.FixedOneKmsManager.<init>(FixedOneKmsManager.java:43)
        at io.openvidu.server.OpenViduServer.kmsManager(OpenViduServer.java:113)
        at io.openvidu.server.OpenViduServer$$EnhancerBySpringCGLIB$$c1fb293b.CGLIB$kmsManager$13(<generated>)
        at io.openvidu.server.OpenViduServer$$EnhancerBySpringCGLIB$$c1fb293b$$FastClassBySpringCGLIB$$f27d8595.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356)
        at io.openvidu.server.OpenViduServer$$EnhancerBySpringCGLIB$$c1fb293b.kmsManager(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
        ... 79 common frames omitted
Caused by: org.kurento.commons.TimeoutRuntimeException: [KurentoClient]  Timeout trying to connect to websocket server ws://localhost:8888/kurento
        at org.kurento.jsonrpc.client.AbstractJsonRpcClientWebSocket.connectIfNecessary(AbstractJsonRpcClientWebSocket.java:857)
        at org.kurento.jsonrpc.client.AbstractJsonRpcClientWebSocket.connect(AbstractJsonRpcClientWebSocket.java:678)
        at org.kurento.client.KurentoClient.<init>(KurentoClient.java:251)
        ... 94 common frames omitted
Caused by: org.kurento.commons.TimeoutRuntimeException: Timeout waiting 25000 millis to acquire lock Server ws://localhost:8888/kurento. The lock is held by thread JsonRpcClient-hearbeatExec-e1-t0
        at org.kurento.commons.TimeoutReentrantLock.tryLockTimeout(TimeoutReentrantLock.java:41)
        at org.kurento.jsonrpc.client.AbstractJsonRpcClientWebSocket.connectIfNecessary(AbstractJsonRpcClientWebSocket.java:844)
        ... 96 common frames omitted
[INFO] 2019-06-25 22:05:38,098 [oopGroup-2-2] org.kurento.jsonrpc.client.JsonRpcClientNettyWebSocket (initChannel) - [KurentoClient]  Initiating new Netty channel. Will create new handler too!
[WARN] 2019-06-25 22:05:38,100 [atExec-e1-t0] org.kurento.jsonrpc.client.JsonRpcClientNettyWebSocket (closeChannel) - [KurentoClient]  Trying to close a JsonRpcClientNettyWebSocket with channel == null
[WARN] 2019-06-25 22:05:38,100 [ntExec-e4-t0] io.openvidu.server.kurento.kms.FixedOneKmsManager (connectionFailed) - Kurento Client failed connecting to KMS with uri ws://localhost:8888/kurento
[WARN] 2019-06-25 22:05:38,100 [atExec-e1-t0] org.kurento.jsonrpc.client.JsonRpcClientNettyWebSocket (closeNativeClient) - [KurentoClient]  Trying to close a JsonRpcClientNettyWebSocket with group == null
[WARN] 2019-06-25 22:05:38,100 [atExec-e1-t0] org.kurento.jsonrpc.client.JsonRpcClient (run) - [KurentoClient]  Error sending heartbeat to server. Exception: [KurentoClient]  Exception connecting to WebSocket server ws://localhost:8888/kurento
[WARN] 2019-06-25 22:05:38,101 [atExec-e1-t0] org.kurento.jsonrpc.client.JsonRpcClient (closeHeartbeatOnFailure) - [KurentoClient]  Stopping heartbeat and closing client: failure during heartbeat mechanism```

**Comment by micaelgallego** [comment] 2019-06-26 07:26
It seems there are a problem connecting from OpenVidu-server to KMS. 

Caused by: org.kurento.commons.exception.KurentoException: Exception connecting to KMS

**Comment by FXschwartz** [comment] 2019-06-26 23:01
@micaelgallego Thanks for the reply, I'll do some more digging and googling with that direction, and if I find anything I will comment in here.

**Comment by TalZiv** [comment] 2019-07-22 12:27
Hi,
I am having the same issue when running Openvidu from docker.
When injecting a shell into the container I can test and connect to the port of kurento, so I can rule
out network connectivity.

any help would be appreciated.

**Comment by pabloFuente** [comment] 2019-07-29 18:58
Closing the issue for now. Please, reopen it if there are any news related to it.

**Closed by pabloFuente** 2019-07-29 18:58 UTC
