### ISSUE TITLE
KMS_URIS in .env causes crash in v2.17.0

### ISSUE THREAD

**Issue by raghuk-botaiml** [OpenVidu/openvidu#614] opened 2021-03-10 21:14 UTC
I just upgraded to v2.17.0 and made all the necessary changes to the .env file. My previous deployment of OpenVidu Pro v2.16.0 had KMS_URIS set in it. I manually added the same to the new .env file. But `./openvidu start` command ends up crashing now.

If I remove this setting then the server starts fine. But I now have to manually open the inspector and add the media node every time the server is restarted (which happens every night on our azure servers for cost reasons).

**Expected behavior**
OpenVidu Server should start without any error and automatically register the media node.

**Wrong current behavior**
OpenVidu Server crashes with the following error:

```
openvidu-server_1  | [ERROR] 2021-03-10 21:03:20,754 [main] org.springframework.boot.SpringApplication - Application run failed
openvidu-server_1  | java.lang.IllegalStateException: Logback configuration error detected:
openvidu-server_1  | ERROR in com.internetitem.logback.elasticsearch.util.ErrorReporter@418c5a9c - Internal error handling log data: java.lang.StringIndexOutOfBoundsException: String index out of range: 0 java.lang.RuntimeException: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
openvidu-server_1  |    at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:169)
openvidu-server_1  |    at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:80)
openvidu-server_1  |    at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:60)
openvidu-server_1  |    at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:118)
openvidu-server_1  |    at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:306)
openvidu-server_1  |    at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:281)
openvidu-server_1  |    at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:239)
openvidu-server_1  |    at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:216)
openvidu-server_1  |    at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
openvidu-server_1  |    at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
openvidu-server_1  |    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
openvidu-server_1  |    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
openvidu-server_1  |    at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:80)
openvidu-server_1  |    at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
openvidu-server_1  |    at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:345)
openvidu-server_1  |    at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
openvidu-server_1  |    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
openvidu-server_1  |    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
openvidu-server_1  |    at io.openvidu.server.pro.OpenViduServerPro.checkKmsUrisConnections(OpenViduServerPro.java:596)
openvidu-server_1  |    at io.openvidu.server.pro.OpenViduServerPro.main(OpenViduServerPro.java:448)
openvidu-server_1  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
openvidu-server_1  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
openvidu-server_1  |    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
openvidu-server_1  |    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
openvidu-server_1  |    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
openvidu-server_1  |    at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
openvidu-server_1  |    at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
openvidu-server_1  |    at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
openvidu-server_1  | Exception in thread "main" java.lang.reflect.InvocationTargetException
openvidu-server_1  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
openvidu-server_1  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
openvidu-server_1  |    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
openvidu-server_1  |    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
openvidu-server_1  |    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
openvidu-server_1  |    at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
openvidu-server_1  |    at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
openvidu-server_1  |    at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
openvidu-server_1  | Caused by: java.lang.IllegalStateException: Logback configuration error detected:
openvidu-server_1  | ERROR in com.internetitem.logback.elasticsearch.util.ErrorReporter@418c5a9c - Internal error handling log data: java.lang.StringIndexOutOfBoundsException: String index out of range: 0 java.lang.RuntimeException: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
openvidu-server_1  |    at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:169)
openvidu-server_1  |    at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:80)
openvidu-server_1  |    at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:60)
openvidu-server_1  |    at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:118)
openvidu-server_1  |    at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:306)
openvidu-server_1  |    at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:281)
openvidu-server_1  |    at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:239)
openvidu-server_1  |    at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:216)
openvidu-server_1  |    at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
openvidu-server_1  |    at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
openvidu-server_1  |    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
openvidu-server_1  |    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
openvidu-server_1  |    at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:80)
openvidu-server_1  |    at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
openvidu-server_1  |    at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:345)
openvidu-server_1  |    at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
openvidu-server_1  |    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
openvidu-server_1  |    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
openvidu-server_1  |    at io.openvidu.server.pro.OpenViduServerPro.checkKmsUrisConnections(OpenViduServerPro.java:596)
openvidu-server_1  |    at io.openvidu.server.pro.OpenViduServerPro.main(OpenViduServerPro.java:448)
openvidu-server_1  |    ... 8 more
```

**OpenVidu deployment info**
- Azure deployment using On Premise method as explained in OpenVidu Docs (https://docs.openvidu.io/en/2.17.0/openvidu-pro/deployment/on-premises/#2-openvidu-server-pro-node)

**Screenshots**
![image](https://user-images.githubusercontent.com/64590389/110698400-9d4d2400-8213-11eb-937f-255d491389ca.png)

**Comment by cruizba** [comment] 2021-03-10 23:38
I've restarted our infrastructure with 2.17.0 and is working fine. Maybe the problem is not that, could you please execute this command and report the result?
```
./openvidu version
```

Also it would be helpful to see the .env file

**Comment by raghuk-botaiml** [comment] 2021-03-11 00:08
Here is the result of `./openvidu version`:

```
Openvidu Information:

  Installation Type: On Premises
  Openvidu Version: 2.17.0
  Openvidu Call Version: 2.17.0

System Information:

  Linux Version:
    - Description:      Ubuntu 18.04.5 LTS
  Docker Version: 20.10.5
  Docker Compose Version: 1.27.4

Installation Information:

  Installation Folder: /opt/openvidu
  Installation Folder Tree:

         |-docker-compose.yml
         |-elasticsearch
         | |-nodes
         | | |-0
         |-certificates
         | |-archive
         | | |-vkyc-rtc-svr.southindia.cloudapp.azure.com
         | | | |-cert1.pem
         | | | |-chain1.pem
         | | | |-fullchain1.pem
         | | | |-privkey1.pem
         | |-keys
         | | |-0000_key-certbot.pem
         | |-renewal-hooks
         | | |-deploy
         | | |-pre
         | | |-post
         | |-renewal
         | | |-vkyc-rtc-svr.southindia.cloudapp.azure.com.conf
         | |-csr
         | | |-0000_csr-certbot.pem
         | |-accounts
         | | |-acme-v02.api.letsencrypt.org
         | | | |-directory
         | | | | |-35e044c394b7cfbab085d057ede3bf1b
         | | | | | |-regr.json
         | | | | | |-private_key.json
         | | | | | |-meta.json
         | |-live
         | | |-certificates.conf
         | | |-vkyc-rtc-svr.southindia.cloudapp.azure.com
         | | | |-privkey.pem
         | | | |-chain.pem
         | | | |-fullchain.pem
         | | | |-cert.pem
         | | | |-README
         | | |-README
         |-cdr
         |-owncert
         |-.env
         |-cluster
         | |-aws
         | | |-openvidu_launch_kms.sh
         | | |-openvidu_drop.sh
         | | |-openvidu_autodiscover.sh
         |-openvidu
         |-custom-layout
         |-docker-compose.override.yml
         |-beats
         | |-filebeat.yml
         | |-metricbeat.yml
         |-custom-nginx-vhosts

Docker Running Services:

  CONTAINER ID   IMAGE                                                 COMMAND                  CREATED       STATUS       PORTS                              NAMES
        9a087482ebe4   openvidu/openvidu-coturn:3.0.0                        "/usr/local/bin/entr…"   2 hours ago   Up 2 hours                                      openvidu_coturn_1
        ad06b33bdd14   openvidu/openvidu-call:2.17.0                         "docker-entrypoint.s…"   2 hours ago   Up 2 hours                                      openvidu_app_1
        867f5438dbd7   openvidu/openvidu-server-pro:2.17.0                   "/usr/local/bin/entr…"   2 hours ago   Up 2 hours                                      openvidu_openvidu-server_1
        9e43b0eee89d   docker.elastic.co/beats/metricbeat-oss:7.8.0          "/usr/local/bin/dock…"   2 hours ago   Up 2 hours                                      openvidu_metricbeat_1
        fe05bf085f21   openvidu/openvidu-proxy:5.0.0                         "/docker-entrypoint.…"   2 hours ago   Up 2 hours                                      openvidu_nginx_1
        72b92be0d4df   openvidu/openvidu-redis:2.0.0                         "docker-entrypoint.s…"   2 hours ago   Up 2 hours                                      openvidu_redis_1
        00bf812ce28e   docker.elastic.co/beats/filebeat-oss:7.8.0            "/usr/local/bin/dock…"   2 hours ago   Up 2 hours                                      openvidu_filebeat_1
        f07908a5d2b8   docker.elastic.co/elasticsearch/elasticsearch:7.8.0   "/tini -- /usr/local…"   2 hours ago   Up 2 hours   0.0.0.0:9200->9200/tcp, 9300/tcp   openvidu_elasticsearch_1
        d5048a0b4d18   docker.elastic.co/kibana/kibana:7.8.0                 "/usr/local/bin/dumb…"   2 hours ago   Up 2 hours   0.0.0.0:5601->5601/tcp             openvidu_kibana_1
```

[.env file as requested](https://github.com/OpenVidu/openvidu/files/6119540/openvidu.env.txt)

Thanks,
Raghu

**Comment by cruizba** [comment] 2021-03-12 22:56
You're right. I've executed your .env file and it is failing.

I've discovered your issue. The special characters in the `ELASTICSEARCH_PASSWORD` is breaking something in the parser. If you change `ELASTICSEARCH_PASSOWORD` to another one with alphanumeric characters (`[a-zA-Z0-9_-]+`), the problem is fixed.

I will close the issue with your feedback.

Regards

**Comment by raghuk-botaiml** [comment] 2021-03-13 10:14
@cruizba changing the kibana password fixed it. But I would still call this a regression bug because that same password work in v2.15 and v2.16. So this issue is new to v2.17. Only the secret key had similar restrictions earlier.

**Closed** 2021-05-22 18:33 UTC
Labels: bug
