### ISSUE TITLE
Audio Volume Detection - Fails on Subscribe "Cannot read property 'jquery' of undefined"

### ISSUE THREAD

**Issue by carter-dewey** [OpenVidu/openvidu#366] opened 2019-12-03 20:17 UTC
**OpenVidu Version (Browser/Node/Server)**
2.11.0

**Describe the bug**
OpenVidu bugs out when attempting to listen to the streamAudioVolumeChange event on either subscribers or publishers.

**Expected behavior**
I should be able to subscribe to the events without getting an error.

I am attempting to subscribe to the event as such

```
subscriber.on('streamAudioVolumeChange', (event : any) => {
   console.log('Subscriber audio volume change from ' + event.value.oldValue + ' to' + event.value.newValue);
});
```

OR

```
publisher.on('streamAudioVolumeChange', (event : any) => {
    console.log('Publisher audio volume change from ' + event.value.oldValue + ' to' + event.value.newValue);
});
```

**Wrong current behavior**
The mothod errors out, Console Error + Stack Trace:
core.js:9110 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'jquery' of undefined
TypeError: Cannot read property 'jquery' of undefined
    at push../node_modules/openvidu-browser/node_modules/hark/hark.js.module.exports (hark.js:48)
    at Stream.push../node_modules/openvidu-browser/lib/OpenVidu/Stream.js.Stream.setSpeechEventIfNotExists (Stream.js:390)
    at Stream.push../node_modules/openvidu-browser/lib/OpenVidu/Stream.js.Stream.enableVolumeChangeEvent (Stream.js:456)
    at Subscriber.push../node_modules/openvidu-browser/lib/OpenVidu/StreamManager.js.StreamManager.on (StreamManager.js:125)
    at openvidu.service.ts:82
    at EventEmitter.<anonymous> (Session.js:476)
    at EventEmitter.emitEvent (EventEmitter.js:394)
    at afterConnectionFound (Session.js:589)
    at Session.js:608
    at ZoneDelegate.invoke (zone-evergreen.js:359)
    at resolvePromise (zone-evergreen.js:797)
    at zone-evergreen.js:862
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Object.onInvokeTask (core.js:34182)
    at ZoneDelegate.invokeTask (zone-evergreen.js:390)
    at Zone.runTask (zone-evergreen.js:168)
    at drainMicroTaskQueue (zone-evergreen.js:559)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:469)
    at invokeTask (zone-evergreen.js:1603)
    at WebSocket.globalZoneAwareCallback (zone-evergreen.js:1629)

**OpenVidu tutorial where to replicate the error**
No current tutorial demonstrates this feature but it is mentioned on your website here:
https://openvidu.io/docs/advanced-features/speech-detection/

**OpenVidu deployment info**
- Deployed in AWS on a custom Ubuntu server. Not via cloud formation.
(https://openvidu.io/docs/deployment/deploying-ubuntu/)

> **IMPORTANT NOTE**: please, if you think the bug might be related to OpenVidu Server side
-I believe this is only related to OpenVidu-Browser

**Client device info (if applicable)**
Describe the client device(s) or platform(s) where you are able to replicate the error. For example:
- Chrome 78.0.3904.97 (Official Build) (64-bit) on Windows 10 (1903).

**Screenshots**
None this is a console error.

**Additional context**
Every other feature of OpenVidu appears to be working as expected. And when I remove any publisher.on('streamAudioVolumeChange') or subscriber.on('streamAudioVolumeChange') I am able to host a perfect video conference.

**Comment by pabloFuente** [comment] 2019-12-03 23:41
Hello,
If you add the streamAudioVolumeChange event to any of the tutorials (openvifu-hello-world should be sufficient), does this bug happen?
If so, we'll be able to replicate it and fix it very quickly.

Regards.

**Comment by carter-dewey** [comment] 2019-12-04 15:55
I'll throw one together and post a link today.

**Comment by pabloFuente** [comment] 2019-12-04 15:57
I've just confirmed the bug exists. Working on it now. And also related to this issue someone opened and closed time ago: https://github.com/OpenVidu/openvidu/issues/162

**Comment by carter-dewey** [comment] 2019-12-04 16:46
Damn you beat me too it but all the same here is my hello-world example. https://github.com/carter-dewey/openvidu-audio-volume-detection-error

**Comment by carter-dewey** [comment] 2019-12-04 16:49
I have read through #162 before but it does not seem to reach a conclusion. Thank you for looking into this so promptly. As soon as there is a fix I will test it out on my side. Have a good one.

**Comment by pabloFuente** [comment] 2019-12-04 16:58
The problem is pretty simple: calling the `on` method on Publishers or Subscribers for this event when the associated MediaStream is not already available causes a "NullPointerException" in the hark library (which is the package used to listen to this kind of audio events).
For a quick fix in the meantime, should be enough to call the `on` event after event `streamPlaying` has been triggered, for example (see [docs](https://openvidu.io/api/openvidu-browser/classes/streammanagerevent.html)). At that point the internal MediaStream will be perfectly defined.

**Comment by carter-dewey** [comment] 2019-12-04 20:02
Thank you that did it!

**Comment by carter-dewey** [comment] 2019-12-04 20:03
For anybody who come along here was my fix.

Convert this
`publisher.on('streamAudioVolumeChange', (event : any) => {
              console.log('Publisher audio volume change from ' + event.value.oldValue + ' to' + event.value.newValue);
            });`

To this

`publisher.on('streamPlaying', (event : any) => {
            publisher.on('streamAudioVolumeChange', (event : any) => {
              console.log('Publisher audio volume change from ' + event.value.oldValue + ' to' + event.value.newValue);
            });
          });`

**Comment by pabloFuente** [comment] 2019-12-05 13:30
Ok, last commit 78ffeca860ff90524a8660192252146dea68a3c4 should fix this issue. Will be available in the next release. 

You can try the fix with the latest compiled version available [here](https://gist.githubusercontent.com/pabloFuente/69e2221bc924e66cfebe94a6594a6fc8/raw/e73d88baa828a943ecabee992b99172d3d5f5101/openvidu-browser-2.11.0-FIX.min.js). If the problem is solved with the old version of your code (which is the right one, not the event-inside-event quick fix I provided), then we will close this issue. Please, tell me if the problem is gone in your case.

Regards!

**Comment by pabloFuente** [comment] 2020-01-03 10:17
Closing the issue. It has been proven to be fixed in the master branch. Will be available in next release.

**Closed by pabloFuente** 2020-01-03 10:17 UTC
Labels: bug

**Comment by Flamenco** [comment] 2021-12-27 19:14
I was having an issue getting `this.speechEvent is undefined`, but i was using the generic session `on` handler.  So the workaround of `streamPlaying` is not available.

` this.session.on('publisherStartSpeaking', (event: PublisherSpeakingEvent) => {} `

@pabloFuente  Will the latest fix solve this problem?

**Comment by micaelgallego** [comment] 2022-01-07 18:08
@Flamenco the issue was closed more than a year ago.

Please try the latest version and create a new issue if you found any problem with latest version.

**Comment by Flamenco** [comment] 2022-01-07 18:21
@micaelgallego  Yes seems like it was fixed in the publisher/subscriber, but not in the session.

**Comment by micaelgallego** [comment] 2022-01-07 18:28
Then please open a new issue to better track the remaining problem

**Comment by Flamenco** [comment] 2022-01-15 16:04
@micaelgallego  When I delay registering `publisherStartSpeaking` to after `streamCreated` it works like a charm.  So probably better to just **document** that.

Working 
```js
this.publisher.on('streamCreated', event => {        
  this.publisher.on('publisherStartSpeaking', (event: PublisherSpeakingEvent) => {
  });

  this.publisher.on('publisherStopSpeaking', (event: PublisherSpeakingEvent) => {
  });
})
```

Not Working
```js
```js
this.publisher.on('streamCreated', event => {        
})
this.publisher.on('publisherStartSpeaking', (event: PublisherSpeakingEvent) => {
});

this.publisher.on('publisherStopSpeaking', (event: PublisherSpeakingEvent) => {
});
```
